# Generated by Django 5.1.3 on 2024-11-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_institution', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('debt_type', models.CharField(choices=[('PERSONAL_LOAN', 'Personal Loan'), ('MORTGAGE', 'Mortgage'), ('STUDENT_LOAN', 'Student Loan'), ('CREDIT_CARD', 'Credit Card'), ('BUSINESS_LOAN', 'Business Loan'), ('AUTO_LOAN', 'Auto Loan'), ('FRIENDS_FAMILY', 'Borrowed from Friends/Family'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Original amount of the debt', max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, help_text='Current unpaid amount of the debt', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate as a percentage (e.g., 5.5 for 5.5%)', max_digits=5)),
                ('start_date', models.DateField(help_text='Start date of the debt')),
                ('has_emis', models.BooleanField(default=False)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_installments', models.IntegerField(help_text='Total number of installments')),
                ('installments_paid', models.IntegerField(help_text='number of installments paid')),
                ('due_date', models.DateField(blank=True, help_text='Due date or maturity date of the debt', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('currency', models.CharField(default='USD', help_text='Currency of the debt', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the debt')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debt.lender')),
            ],
        ),
    ]
