# Generated by Django 5.1.3 on 2024-11-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
